In [1]:
# import dependencies
import pandas as pd

In [2]:
# read in csv file
file = "Resources/listings.csv"
df = pd.read_csv(file)
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2441,https://www.airbnb.com/rooms/2441,20230323061033,2023-03-23,city scrape,"Cozy Artist’s Abode, NE Mpls - Pets, Wifi, Rok...",Make my home your homebase while you check out...,The area: <br /> Welcome to NE Minneapolis...,https://a0.muscache.com/pictures/514b9a70-c353...,2680,...,4.93,4.80,4.71,STR-111974,f,2,2,0,0,1.82
1,2396616,https://www.airbnb.com/rooms/2396616,20230323061033,2023-03-23,city scrape,The Cathedral Suite,The Cathedral Suite is a beautiful corner towe...,"We are situated in a quiet, leafy neighborhood...",https://a0.muscache.com/pictures/5b465faf-565b...,12243618,...,4.97,5.00,4.91,2011-008637,t,4,0,4,0,0.55
2,2437421,https://www.airbnb.com/rooms/2437421,20230323061033,2023-03-23,city scrape,The Storybook Suite,The Storybook Suite is a spacious guest suite ...,"We are situated in a quiet, leafy neighborhood...",https://a0.muscache.com/pictures/eea165b8-dcd1...,12243618,...,5.00,5.00,5.00,2011-008637,t,4,0,4,0,0.17
3,2461261,https://www.airbnb.com/rooms/2461261,20230323061033,2023-03-23,city scrape,Bedroom in family home,Home is in friendly kept-up neighborhood. It'...,The neighborhood is a great family-friendly ar...,https://a0.muscache.com/pictures/32619894/702a...,12585390,...,4.97,4.86,4.63,20170004580,f,2,0,2,0,0.35
4,2590405,https://www.airbnb.com/rooms/2590405,20230323061033,2023-03-23,city scrape,Get Cozy in our Fabulous Uptown Home,Uptown is the perfect place to land for your t...,This is a unique urban neighborhood within wal...,https://a0.muscache.com/pictures/miso/Hosting-...,115268,...,5.00,5.00,4.67,STR-400717,f,3,3,0,0,0.09

In [3]:
# display columns in df
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [4]:
# drop columns from df
newDF = df.drop(columns = ['scrape_id', 'last_scraped', 'source','description', 'neighborhood_overview', 'picture_url',\
                  'host_url', 'host_name', 'host_since', 'host_location', 'host_about','host_thumbnail_url', 'host_picture_url',\
                  'host_verifications','host_has_profile_pic', 'host_identity_verified','bathrooms','minimum_nights',\
                   'maximum_nights', 'minimum_minimum_nights','maximum_minimum_nights', 'minimum_maximum_nights','maximum_maximum_nights',\
                    'minimum_nights_avg_ntm','maximum_nights_avg_ntm', 'calendar_updated','neighbourhood_group_cleansed','calendar_last_scraped',\
                   'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review','last_review','review_scores_accuracy',\
                   'license', 'instant_bookable','calculated_host_listings_count','calculated_host_listings_count_entire_homes',\
                   'calculated_host_listings_count_private_rooms','calculated_host_listings_count_shared_rooms', 'reviews_per_month','host_neighbourhood',\
                    'host_response_time', 'host_response_rate', 'host_acceptance_rate','neighbourhood','host_listings_count','beds'
                  ])

In [5]:
# display df
newDF.head()

,id,listing_url,name,host_id,host_is_superhost,host_total_listings_count,neighbourhood_cleansed,latitude,longitude,property_type,...,availability_60,availability_90,availability_365,number_of_reviews,review_scores_rating,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,2441,https://www.airbnb.com/rooms/2441,"Cozy Artist’s Abode, NE Mpls - Pets, Wifi, Rok...",2680,t,2,Hennepin,45.00862,-93.23424,Entire home,...,24,24,24,298,4.80,4.72,4.93,4.93,4.80,4.71
1,2396616,https://www.airbnb.com/rooms/2396616,The Cathedral Suite,12243618,t,4,Ramsey,44.94655,-93.11327,Room in boutique hotel,...,51,78,350,35,5.00,5.00,4.91,4.97,5.00,4.91
2,2437421,https://www.airbnb.com/rooms/2437421,The Storybook Suite,12243618,t,4,Ramsey,44.94707,-93.11483,Room in boutique hotel,...,54,82,348,16,5.00,5.00,5.00,5.00,5.00,5.00
3,2461261,https://www.airbnb.com/rooms/2461261,Bedroom in family home,12585390,t,2,Ramsey,44.94293,-93.14990,Private room in home,...,20,50,325,37,4.62,3.97,5.00,4.97,4.86,4.63
4,2590405,https://www.airbnb.com/rooms/2590405,Get Cozy in our Fabulous Uptown Home,115268,t,4,Hennepin,44.94435,-93.30252,Entire home,...,58,81,114,6,5.00,5.00,5.00,5.00,5.00,4.67

In [6]:
# check data types
newDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4765 entries, 0 to 4764
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           4765 non-null   int64
 1   listing_url                  4765 non-null   object
 2   name                         4765 non-null   object
 3   host_id                      4765 non-null   int64
 4   host_is_superhost            4764 non-null   object
 5   host_total_listings_count    4765 non-null   int64
 6   neighbourhood_cleansed       4765 non-null   object
 7   latitude                     4765 non-null   float64
 8   longitude                    4765 non-null   float64
 9   property_type                4765 non-null   object
 10  room_type                    4765 non-null   object
 11  accommodates                 4765 non-null   int64
 12  bathrooms_text               4759 non-null   object
 13  bedrooms                     4583 non-null   float64
 14  amenities                    4765 non-null   object
 15  price                        4765 non-null   object
 16  has_availability             4765 non-null   object
 17  availability_30              4765 non-null   int64
 18  availability_60              4765 non-null   int64
 19  availability_90              4765 non-null   int64
 20  availability_365             4765 non-null   int64
 21  number_of_reviews            4765 non-null   int64
 22  review_scores_rating         3884 non-null   float64
 23  review_scores_cleanliness    3879 non-null   float64
 24  review_scores_checkin        3879 non-null   float64
 25  review_scores_communication  3879 non-null   float64
 26  review_scores_location       3879 non-null   float64
 27  review_scores_value          3879 non-null   float64
dtypes: float64(9), int64(9), object(10)
memory usage: 1.0+ MB

In [7]:
# drop null values
newDF = newDF.dropna()

In [8]:
# change data type of super host from object to boolean
newDF['host_is_superhost'] = newDF['host_is_superhost'].map({'t': True, 'f': False})

In [9]:
# import regex to remove letters from bathroom_text
import re
newDF['bathrooms_text'] = newDF['bathrooms_text'].str.replace(r'\D+','0', regex=True)

In [10]:
# fill blank values
newDF.fillna(method='pad')

,id,listing_url,name,host_id,host_is_superhost,host_total_listings_count,neighbourhood_cleansed,latitude,longitude,property_type,...,availability_60,availability_90,availability_365,number_of_reviews,review_scores_rating,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,2441,https://www.airbnb.com/rooms/2441,"Cozy Artist’s Abode, NE Mpls - Pets, Wifi, Rok...",2680,True,2,Hennepin,45.00862,-93.23424,Entire home,...,24,24,24,298,4.80,4.72,4.93,4.93,4.80,4.71
1,2396616,https://www.airbnb.com/rooms/2396616,The Cathedral Suite,12243618,True,4,Ramsey,44.94655,-93.11327,Room in boutique hotel,...,51,78,350,35,5.00,5.00,4.91,4.97,5.00,4.91
2,2437421,https://www.airbnb.com/rooms/2437421,The Storybook Suite,12243618,True,4,Ramsey,44.94707,-93.11483,Room in boutique hotel,...,54,82,348,16,5.00,5.00,5.00,5.00,5.00,5.00
3,2461261,https://www.airbnb.com/rooms/2461261,Bedroom in family home,12585390,True,2,Ramsey,44.94293,-93.14990,Private room in home,...,20,50,325,37,4.62,3.97,5.00,4.97,4.86,4.63
4,2590405,https://www.airbnb.com/rooms/2590405,Get Cozy in our Fabulous Uptown Home,115268,True,4,Hennepin,44.94435,-93.30252,Entire home,...,58,81,114,6,5.00,5.00,5.00,5.00,5.00,4.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4760,2261339,https://www.airbnb.com/rooms/2261339,NeoEden's Sage Room-(Upstairs),8562602,False,11,Hennepin,44.95609,-93.28915,Private room in home,...,60,90,365,40,4.59,4.26,4.51,4.62,4.85,4.69
4761,2266340,https://www.airbnb.com/rooms/2266340,Emma’s Spectacle Lake Home,11572783,False,1,Isanti,45.57124,-93.40412,Entire home,...,53,83,343,2,5.00,5.00,5.00,5.00,5.00,5.00
4762,2268111,https://www.airbnb.com/rooms/2268111,"RIVER FALLS - walk to town, Kinni river, Glen ...",11549522,True,1,Pierce,44.84892,-92.63569,Private room in home,...,47,77,179,91,4.89,4.97,4.98,4.96,4.94,4.78
4763,2310965,https://www.airbnb.com/rooms/2310965,Nice cozy house near Como Park,10294911,True,1,Ramsey,44.98136,-93.13324,Entire home,...,0,0,105,25,4.68,4.36,4.84,4.80,4.96,4.64
4764,2356359,https://www.airbnb.com/rooms/2356359,Unique Mid-Century Modern in a Great Neighborhood,12032844,True,6,Ramsey,44.98661,-93.19998,Entire home,...,10,18,114,417,4.93,4.84,4.98,4.98,4.94,4.86

In [11]:
# drop null values
newDF = newDF.dropna()

In [12]:
# Convert data type to float
newDF['bathrooms_text'] = newDF['bathrooms_text'].astype(float)
newDF.rename(columns = {'bathrooms_text':'bathrooms'}, inplace = True)

In [13]:
newDF.rename(columns = {'neighbourhood_cleansed':'county'},inplace=True)

In [14]:
# convert price to float
newDF['price'] = newDF['price'].str.replace(',', '',regex=True).str.replace('$','',regex=True)

In [15]:
newDF['price'] = newDF['price'].astype(float)

In [16]:
# change data type of 'has_avaliability' from object to boolean
newDF['has_availability'] = newDF['has_availability'].map({'t': True, 'f': False})

In [17]:
newDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3728 entries, 0 to 4764
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           3728 non-null   int64
 1   listing_url                  3728 non-null   object
 2   name                         3728 non-null   object
 3   host_id                      3728 non-null   int64
 4   host_is_superhost            3728 non-null   bool
 5   host_total_listings_count    3728 non-null   int64
 6   county                       3728 non-null   object
 7   latitude                     3728 non-null   float64
 8   longitude                    3728 non-null   float64
 9   property_type                3728 non-null   object
 10  room_type                    3728 non-null   object
 11  accommodates                 3728 non-null   int64
 12  bathrooms                    3728 non-null   float64
 13  bedrooms                     3728 non-null   float64
 14  amenities                    3728 non-null   object
 15  price                        3728 non-null   float64
 16  has_availability             3728 non-null   bool
 17  availability_30              3728 non-null   int64
 18  availability_60              3728 non-null   int64
 19  availability_90              3728 non-null   int64
 20  availability_365             3728 non-null   int64
 21  number_of_reviews            3728 non-null   int64
 22  review_scores_rating         3728 non-null   float64
 23  review_scores_cleanliness    3728 non-null   float64
 24  review_scores_checkin        3728 non-null   float64
 25  review_scores_communication  3728 non-null   float64
 26  review_scores_location       3728 non-null   float64
 27  review_scores_value          3728 non-null   float64
dtypes: bool(2), float64(11), int64(9), object(6)
memory usage: 793.7+ KB

In [18]:
# newDF.to_csv('Resources/dataframe.csv',index=False)

In [19]:
import sqlite3

In [20]:
connection= sqlite3.connect('abnb.sqlite')

In [21]:
newDF.to_sql('bnb_dset',connection,if_exists='replace',dtype={'id':'INTEGER PRIMARY KEY'})

3728

In [22]:
#!mongoimport --type csv -d AirBnB -c listings --drop -- dataframe.csv

In [23]:
newDF

,id,listing_url,name,host_id,host_is_superhost,host_total_listings_count,county,latitude,longitude,property_type,...,availability_60,availability_90,availability_365,number_of_reviews,review_scores_rating,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,2441,https://www.airbnb.com/rooms/2441,"Cozy Artist’s Abode, NE Mpls - Pets, Wifi, Rok...",2680,True,2,Hennepin,45.00862,-93.23424,Entire home,...,24,24,24,298,4.80,4.72,4.93,4.93,4.80,4.71
1,2396616,https://www.airbnb.com/rooms/2396616,The Cathedral Suite,12243618,True,4,Ramsey,44.94655,-93.11327,Room in boutique hotel,...,51,78,350,35,5.00,5.00,4.91,4.97,5.00,4.91
2,2437421,https://www.airbnb.com/rooms/2437421,The Storybook Suite,12243618,True,4,Ramsey,44.94707,-93.11483,Room in boutique hotel,...,54,82,348,16,5.00,5.00,5.00,5.00,5.00,5.00
3,2461261,https://www.airbnb.com/rooms/2461261,Bedroom in family home,12585390,True,2,Ramsey,44.94293,-93.14990,Private room in home,...,20,50,325,37,4.62,3.97,5.00,4.97,4.86,4.63
4,2590405,https://www.airbnb.com/rooms/2590405,Get Cozy in our Fabulous Uptown Home,115268,True,4,Hennepin,44.94435,-93.30252,Entire home,...,58,81,114,6,5.00,5.00,5.00,5.00,5.00,4.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4760,2261339,https://www.airbnb.com/rooms/2261339,NeoEden's Sage Room-(Upstairs),8562602,False,11,Hennepin,44.95609,-93.28915,Private room in home,...,60,90,365,40,4.59,4.26,4.51,4.62,4.85,4.69
4761,2266340,https://www.airbnb.com/rooms/2266340,Emma’s Spectacle Lake Home,11572783,False,1,Isanti,45.57124,-93.40412,Entire home,...,53,83,343,2,5.00,5.00,5.00,5.00,5.00,5.00
4762,2268111,https://www.airbnb.com/rooms/2268111,"RIVER FALLS - walk to town, Kinni river, Glen ...",11549522,True,1,Pierce,44.84892,-92.63569,Private room in home,...,47,77,179,91,4.89,4.97,4.98,4.96,4.94,4.78
4763,2310965,https://www.airbnb.com/rooms/2310965,Nice cozy house near Como Park,10294911,True,1,Ramsey,44.98136,-93.13324,Entire home,...,0,0,105,25,4.68,4.36,4.84,4.80,4.96,4.64
4764,2356359,https://www.airbnb.com/rooms/2356359,Unique Mid-Century Modern in a Great Neighborhood,12032844,True,6,Ramsey,44.98661,-93.19998,Entire home,...,10,18,114,417,4.93,4.84,4.98,4.98,4.94,4.86

In [24]:
df_t=newDF['review_scores_location'].unique()
df_t

array([4.8 , 5.  , 4.86, 4.94, 4.85, 4.77, 4.92, 4.95, 4.91, 4.88, 4.84,
       4.97, 4.64, 4.99, 4.93, 4.9 , 4.98, 4.82, 4.89, 4.68, 4.  , 4.72,
       4.79, 4.96, 4.81, 4.44, 4.48, 4.54, 4.52, 4.47, 4.61, 4.87, 4.78,
       4.75, 4.5 , 4.56, 4.65, 4.83, 4.55, 4.62, 4.66, 4.69, 4.33, 4.67,
       4.59, 4.71, 4.76, 1.  , 3.93, 2.75, 4.14, 4.63, 4.74, 4.73, 4.53,
       4.36, 3.67, 4.26, 4.2 , 4.7 , 4.25, 4.05, 4.06, 3.92, 4.16, 2.67,
       4.4 , 2.  , 4.51, 4.42, 4.58, 4.57, 4.6 , 4.43, 4.46, 4.49, 4.23,
       4.22, 4.29, 4.37, 3.75, 3.2 , 4.35, 4.18, 4.38, 4.31, 3.97, 4.09,
       4.17, 4.41, 3.  , 4.3 , 3.5 , 4.28, 4.27, 3.91, 3.63, 4.39, 3.71,
       3.6 , 4.11, 3.9 , 4.45, 4.21, 3.94, 3.8 , 3.86, 4.32])

In [25]:
newDF.groupby(['county'])[["price","review_scores_cleanliness"]].mean()

                 price  review_scores_cleanliness
county
Anoka       184.748299                   4.797959
Carver      301.000000                   4.824286
Chisago     225.600000                   4.823867
Dakota      191.860606                   4.763515
Hennepin    158.632840                   4.812300
Isanti      228.130435                   4.880435
Le Sueur    286.937500                   4.923750
Mille Lacs  280.816901                   4.770282
Pierce      255.697674                   4.910000
Ramsey      138.952510                   4.785237
Scott       195.142857                   4.695238
Sherburne   140.557377                   4.800328
Sibley      132.750000                   4.995000
St. Croix   310.491228                   4.840351
Washington  280.953757                   4.855780
Wright      200.103093                   4.813093

In [26]:
newDF['county'].value_counts()

Hennepin      1961
Ramsey         737
Washington     173
Dakota         165
Anoka          147
Wright          97
Chisago         75
Mille Lacs      71
Sherburne       61
St. Croix       57
Carver          56
Pierce          43
Scott           42
Isanti          23
Le Sueur        16
Sibley           4
Name: county, dtype: int64